pipeline {
    
    agent any

    tools {
        maven "MAVEN"
        jdk "JDK"
    }
environment {
      registry = "devopshint/dockerimg-test"
      registryCredential = 'dockerhub'
      dockerImage = ''
  }
    stages {
        stage('Initialize'){
            steps {
                echo "PATH = ${M2_HOME}/bin:${PATH}"
                echo "M2_HOME = /opt/maven"
            }
        }
        stage('Build') {
            steps {
                dir("/var/lib/jenkins/workspace/demopipelinetask/my-app") {
                sh 'mvn -B -DskipTests clean package'
                }

            }
        }
        stage('Cloning Git') {
          steps {
            git 'https://github.com/akashpadwal/jenkins-pipeline-example.git'
          }
        }
    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build registry + ":$BUILD_NUMBER"
        }
      }
    }
    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
          }
        }
      }
    }
    stage('Remove Unused docker image') {
      steps{
        sh "docker rmi $registry:$BUILD_NUMBER"
      }
    }

        }
     }
    post {
       always {
          junit(
        allowEmptyResults: true,
        testResults: '*/test-reports/.xml'
      )
      }
   } 
