pipeline {
    
    agent any

    tools {
        maven "MAVEN"
        jdk "JDK"
    }
environment {
      registry = "devopshint/jenkins-pipeline"
      registryCredential = 'dockerhub'
      dockerImage = ''
  }
    stages {
        stage('Initialize'){
            steps {
                echo "PATH = ${M2_HOME}/bin:${PATH}"
                echo "M2_HOME = /opt/maven"
            }
        }
        stage('Build') {
            steps {
                dir("/var/lib/jenkins/workspace/demopipelinetask/my-app") {
                sh 'mvn -B -DskipTests clean package'
                }

            }
        }
    stage('Create Docker Image') {
      steps {
        script {
    dir('my-app') {
      docker.build("devopshint/jenkins-pipeline:${env.BUILD_NUMBER}")
    }
  }
      }
    }
    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
          }
        }
      }
    }
    stage('Remove Unused docker image') {
      steps{
        sh "docker rmi $registry:$BUILD_NUMBER"
      }
    }

        }
     }
    post {
       always {
          junit(
        allowEmptyResults: true,
        testResults: '*/test-reports/.xml'
      )
      }
   }
